### ISSUE TITLE
Exception while invoking method 'sendEmail' TypeError: Object [object Object] has no method 'send'

### ISSUE THREAD

**Issue by vladstan** [Wylio/meteor-mandrill#17]
Hi @dandv, this is an error I got using this package. Everything worked fine, but suddenly I got this error and not working.

Here is the full error:

xception while invoking method 'sendEmail' TypeError: Object [object Object] has no method 'send'
I20160209-16:58:38.857(2)?     at [object Object].Meteor.methods.sendEmail (server/methods.js:13:11)
I20160209-16:58:38.857(2)?     at maybeAuditArgumentChecks (livedata_server.js:1698:12)
I20160209-16:58:38.858(2)?     at livedata_server.js:708:19
I20160209-16:58:38.858(2)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
I20160209-16:58:38.858(2)?     at livedata_server.js:706:40
I20160209-16:58:38.858(2)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
I20160209-16:58:38.858(2)?     at livedata_server.js:704:46
I20160209-16:58:38.859(2)?     at tryCallTwo (/Users/vladstan/.meteor/packages/promise/.0.5.1.8idxpg++os+web.browser+web.cordova/npm/node_modules/meteor-promise/node_modules/promise/lib/core.js:45:5)
I20160209-16:58:38.859(2)?     at doResolve (/Users/vladstan/.meteor/packages/promise/.0.5.1.8idxpg++os+web.browser+web.cordova/npm/node_modules/meteor-promise/node_modules/promise/lib/core.js:171:13)
I20160209-16:58:38.859(2)?     at new Promise (/Users/vladstan/.meteor/packages/promise/.0.5.1.8idxpg++os+web.browser+web.cordova/npm/node_modules/meteor-promise/node_modules/promise/lib/core.js:65:3)

Let me know if you can help me with that. thanks.

**Comment by c316** [comment]
Can you post the code in your method file? I'd like to take a look at what you are doing around line 13.
